apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ms_otp.name }}
  labels:
    app: {{ .Values.ms_otp.name }}
    chart: {{ include "helm-meznger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.ms_otp.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.ms_otp.name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.ms_otp.name }}
        release: {{ .Release.Name }}
    spec:
      containers:

        - name: {{ .Values.ms_otp.name }}
          image: "{{ .Values.ms_otp.image.repository }}:{{ .Values.ms_otp.image.tag }}"
          imagePullPolicy: {{ .Values.ms_otp.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ms_otp.containerPort }}
              protocol: TCP
          env:
          - name: TWILIO_SID
            valueFrom:
              secretKeyRef:
                name: twilio
                key: sid
          - name: TWILIO_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: twilio
                key: authToken
          - name: TWILIO_PHONE_NUMBER
            valueFrom:
              secretKeyRef:
                name: twilio
                key: phoneNumber
