apiVersion: v1
kind: Secret
metadata:
  name: twilio
  chart: {{ include "helm-meznger.chart" . }}
  release: {{ .Release.Name }}
data:
  sid: {{ required "twilio.sid is required, specify with --set twilio.sid=$TWILIO_SID" .Values.twilio.sid | b64enc | quote }}
  authToken: {{ required "twilio.authToken is required, specify with --set twilio.authToken=$TWILIO_AUTH_TOKEN" .Values.twilio.authToken | b64enc | quote }}
  phoneNumber: {{ required "twilio.phoneNumber is required, specify with --set twilio.phoneNumber=$TWILIO_PHONE_NUMBER" .Values.twilio.phoneNumber | b64enc | quote }}
