apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ms_otp.name }}
  labels:
    app: {{ .Values.ms_otp.name }}
    chart: {{ include "helm-meznger.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ms_otp.service.type }}
  ports:
    - port: {{ .Values.ms_otp.service.port }}
      targetPort: {{ .Values.ms_otp.containerPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.ms_otp.name }}
    release: {{ .Release.Name }}
