# The OTP microservice details.
ms_otp:
  name: ms-otp
  replicaCount: 1
  containerPort: 3000
  image:
    repository: meznger/ms-otp
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 3000

# Twilio secrets. Should come from the operator.
twilio:
  sid:
  authToken:
  phoneNumber:
